
server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taotao?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
#    freemarker静态资源配置


  freemarker:
    cache: false #       设定ftl文件路径
    template-loader-path: classpath:/templates
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl





